### ISSUE TITLE
Unknown code for 10:040239: RP/10E0

### ISSUE THREAD

**Issue by phdelodder** [ramses-rf/ramses_rf#13]
```
2021-01-24 18:06:05 ERROR (MainThread) [custom_components.evohome_cc.evohome_rf.message] 049 RP --- 10:040239 18:005567 --:------ 10E0 038 000001C8810B0700FEFFFFFFFFFF140807E35238383230000000000000000000000000000000 < AssertionError
Traceback (most recent call last):
  File "/config/custom_components/evohome_cc/evohome_rf/message.py", line 519, in process_msg
    update_entities(msg, msg._gwy._prev_msg)  # update the state database
  File "/config/custom_components/evohome_cc/evohome_rf/message.py", line 466, in update_entities
    this._gwy.device_by_id[this.src.id]._handle_msg(this)
  File "/config/custom_components/evohome_cc/evohome_rf/devices.py", line 711, in _handle_msg
    super()._handle_msg(msg)
  File "/config/custom_components/evohome_cc/evohome_rf/devices.py", line 221, in _handle_msg
    super()._handle_msg(msg)
  File "/config/custom_components/evohome_cc/evohome_rf/devices.py", line 354, in _handle_msg
    assert (
AssertionError: Unknown code for 10:040239: RP/10E0
```

**Comment by zxdavb** [comment]
I have addressed this issue - a fix will come.
