### ISSUE TITLE
AssertionError: Unknown verb for 10:040239:  I/3EF0

### ISSUE THREAD

**Issue by phdelodder** [ramses-rf/ramses_rf#14]
```
2021-01-25 19:18:17 ERROR (MainThread) [evohome_rf.message] 050  I --- 10:040239 --:------ 10:040239 3EF0 009 0002100A00FF032264 < AssertionError
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/evohome_rf/message.py", line 519, in process_msg
    update_entities(msg, msg._gwy._prev_msg)  # update the state database
  File "/usr/local/lib/python3.8/site-packages/evohome_rf/message.py", line 466, in update_entities
    this._gwy.device_by_id[this.src.id]._handle_msg(this)
  File "/usr/local/lib/python3.8/site-packages/evohome_rf/devices.py", line 733, in _handle_msg
    super()._handle_msg(msg)
  File "/usr/local/lib/python3.8/site-packages/evohome_rf/devices.py", line 226, in _handle_msg
    super()._handle_msg(msg)
  File "/usr/local/lib/python3.8/site-packages/evohome_rf/devices.py", line 380, in _handle_msg
    assert (
AssertionError: Unknown verb for 10:040239:  I/3EF0
```

**Comment by zxdavb** [comment]
So I changed the way I was doing things from before - it introduced some bugs like this, but the fix is really easy - ALl I need to do is change the second last line of the data structure to `"3EF0": [_I, RP],`:
```python
    "10": {
        "10A0": [RP],
        "10E0": [_I, RP],
        "1260": [RP],
        "1290": [RP],
        "1FD4": [_I],
        "22D9": [RP],
        "2349": [_I],
        "3150": [_I],
        "3220": [RP],
        "3EF0": [RP],
        "3EF1": [RP],
    },
```
